import { mutation } from "./_generated/server";

// Seed data for Malaysian hospitals
const malaysianHospitals = [
  {
    name: "Hospital Kuala Lumpur",
    type: "government" as const,
    address: "Jalan Pahang, Titiwangsa",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    postalCode: "50586",
    latitude: 3.1714,
    longitude: 101.7006,
    phoneNumber: "+603-2615 5555",
    emergencyNumber: "+603-2615 5555",
    website: "https://hkl.moh.gov.my",
    email: "hkl@moh.gov.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Neurology", "Oncology", "Orthopedics", "Pediatrics", "Surgery"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "Radiology", "Blood Bank"],
    rating: 4.2,
  },
  {
    name: "Gleneagles Kuala Lumpur",
    type: "private" as const,
    address: "286 & 288, Jalan Ampang",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    postalCode: "50450",
    latitude: 3.1577,
    longitude: 101.7198,
    phoneNumber: "+603-4141 3000",
    emergencyNumber: "+603-4141 3018",
    website: "https://gleneagles.com.my",
    email: "enquiry.gkl@gleneagles.com.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Oncology", "Orthopedics", "Neurology", "Women's Health", "Gastroenterology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "MRI", "CT Scan", "Health Screening"],
    rating: 4.5,
  },
  {
    name: "Sunway Medical Centre",
    type: "private" as const,
    address: "5, Jalan Lagoon Selatan, Bandar Sunway",
    city: "Petaling Jaya",
    state: "Selangor",
    postalCode: "47500",
    latitude: 3.0677,
    longitude: 101.6092,
    phoneNumber: "+603-7491 9191",
    emergencyNumber: "+603-7491 9191",
    website: "https://sunwaymedical.com",
    email: "info@sunwaymedical.com",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Oncology", "Neurology", "Orthopedics", "Pediatrics", "Fertility"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "PET Scan", "Rehabilitation"],
    rating: 4.6,
  },
  {
    name: "Hospital Sultanah Aminah",
    type: "government" as const,
    address: "Jalan Persiaran Abu Bakar Sultan",
    city: "Johor Bahru",
    state: "Johor",
    postalCode: "80100",
    latitude: 1.4634,
    longitude: 103.7468,
    phoneNumber: "+607-223 1666",
    emergencyNumber: "+607-224 6953",
    website: "https://hsajb.moh.gov.my",
    email: "hsajb@moh.gov.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Surgery", "Orthopedics", "Pediatrics", "Obstetrics", "Neurology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "Radiology", "Blood Bank"],
    rating: 4.0,
  },
  {
    name: "Penang General Hospital",
    type: "government" as const,
    address: "Jalan Residensi, Georgetown",
    city: "Georgetown",
    state: "Penang",
    postalCode: "10990",
    latitude: 5.4164,
    longitude: 100.3146,
    phoneNumber: "+604-222 5333",
    emergencyNumber: "+604-222 5333",
    website: "https://hpulau.moh.gov.my",
    email: "hpulau@moh.gov.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Neurology", "Surgery", "Pediatrics", "Oncology", "Orthopedics"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "Radiology", "Dialysis"],
    rating: 4.1,
  },
  {
    name: "Prince Court Medical Centre",
    type: "private" as const,
    address: "39, Jalan Kia Peng",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    postalCode: "50450",
    latitude: 3.1528,
    longitude: 101.7072,
    phoneNumber: "+603-2160 0000",
    emergencyNumber: "+603-2160 0999",
    website: "https://princecourt.com",
    email: "customerservice@princecourt.com",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Oncology", "Orthopedics", "Neurology", "Urology", "Gastroenterology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "MRI", "Executive Health Screening"],
    rating: 4.7,
  },
  {
    name: "Hospital Selayang",
    type: "government" as const,
    address: "Lebuhraya Selayang-Kepong",
    city: "Batu Caves",
    state: "Selangor",
    postalCode: "68100",
    latitude: 3.2563,
    longitude: 101.6444,
    phoneNumber: "+603-6126 3333",
    emergencyNumber: "+603-6126 3333",
    website: "https://hselayang.moh.gov.my",
    email: "hselayang@moh.gov.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Nephrology", "Surgery", "Pediatrics", "Orthopedics", "Oncology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "Dialysis", "Radiology"],
    rating: 4.0,
  },
  {
    name: "Pantai Hospital Kuala Lumpur",
    type: "private" as const,
    address: "8, Jalan Bukit Pantai",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    postalCode: "59100",
    latitude: 3.1162,
    longitude: 101.6687,
    phoneNumber: "+603-2296 0888",
    emergencyNumber: "+603-2296 0999",
    website: "https://pantai.com.my",
    email: "phkl@pantai.com.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Oncology", "Orthopedics", "Women's Health", "Pediatrics", "Surgery"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "MRI", "Health Screening"],
    rating: 4.4,
  },
  {
    name: "Subang Jaya Medical Centre",
    type: "private" as const,
    address: "1, Jalan SS 12/1A, Subang Jaya",
    city: "Subang Jaya",
    state: "Selangor",
    postalCode: "47500",
    latitude: 3.0577,
    longitude: 101.5864,
    phoneNumber: "+603-5639 1212",
    emergencyNumber: "+603-5639 1199",
    website: "https://rfrq.ramsaysimedarby.com",
    email: "sjmc@rfrq.com.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Oncology", "Orthopedics", "Neurology", "Gastroenterology", "Pediatrics"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "MRI", "Rehabilitation"],
    rating: 4.3,
  },
  {
    name: "Hospital Putrajaya",
    type: "government" as const,
    address: "Pusat Pentadbiran Kerajaan Persekutuan, Presint 7",
    city: "Putrajaya",
    state: "Putrajaya",
    postalCode: "62250",
    latitude: 2.9264,
    longitude: 101.6964,
    phoneNumber: "+603-8312 4200",
    emergencyNumber: "+603-8312 4200",
    website: "https://hptj.moh.gov.my",
    email: "hptj@moh.gov.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Surgery", "Pediatrics", "Orthopedics", "Oncology", "Neurology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "Radiology", "Rehabilitation"],
    rating: 4.2,
  },
  {
    name: "KPJ Damansara Specialist Hospital",
    type: "private" as const,
    address: "119, Jalan SS 20/10, Damansara Utama",
    city: "Petaling Jaya",
    state: "Selangor",
    postalCode: "47400",
    latitude: 3.1355,
    longitude: 101.6169,
    phoneNumber: "+603-7718 1000",
    emergencyNumber: "+603-7722 2692",
    website: "https://kpjdamansara.com",
    email: "damansara@kpjhealth.com.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Orthopedics", "Oncology", "Neurology", "Gastroenterology", "Urology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "MRI", "Dialysis"],
    rating: 4.3,
  },
  {
    name: "Hospital Tuanku Ja'afar",
    type: "government" as const,
    address: "Jalan Rasah",
    city: "Seremban",
    state: "Negeri Sembilan",
    postalCode: "70300",
    latitude: 2.7224,
    longitude: 101.9387,
    phoneNumber: "+606-768 4000",
    emergencyNumber: "+606-768 4000",
    website: "https://htjs.moh.gov.my",
    email: "htjs@moh.gov.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Surgery", "Pediatrics", "Orthopedics", "Obstetrics", "Oncology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "Radiology", "Blood Bank"],
    rating: 4.0,
  },
  {
    name: "Island Hospital",
    type: "private" as const,
    address: "308, Macalister Road",
    city: "Georgetown",
    state: "Penang",
    postalCode: "10450",
    latitude: 5.4155,
    longitude: 100.3291,
    phoneNumber: "+604-228 8222",
    emergencyNumber: "+604-228 8111",
    website: "https://islandhospital.com",
    email: "enquiry@islandhospital.com",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Oncology", "Orthopedics", "Neurology", "Gastroenterology", "Women's Health"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "MRI", "Health Screening"],
    rating: 4.5,
  },
  {
    name: "Hospital Queen Elizabeth",
    type: "government" as const,
    address: "Jalan Penampang, Luyang",
    city: "Kota Kinabalu",
    state: "Sabah",
    postalCode: "88200",
    latitude: 5.9749,
    longitude: 116.0724,
    phoneNumber: "+6088-324 600",
    emergencyNumber: "+6088-324 600",
    website: "https://hqe.moh.gov.my",
    email: "hqe@moh.gov.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Surgery", "Pediatrics", "Orthopedics", "Oncology", "Neurology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "Radiology", "Blood Bank"],
    rating: 4.1,
  },
  {
    name: "Sarawak General Hospital",
    type: "government" as const,
    address: "Jalan Hospital",
    city: "Kuching",
    state: "Sarawak",
    postalCode: "93586",
    latitude: 1.5593,
    longitude: 110.3459,
    phoneNumber: "+6082-276 666",
    emergencyNumber: "+6082-276 666",
    website: "https://hus.moh.gov.my",
    email: "hus@moh.gov.my",
    operatingHours: "24 hours",
    is24Hours: true,
    hasEmergency: true,
    specialties: ["Cardiology", "Surgery", "Pediatrics", "Orthopedics", "Oncology", "Neurology"],
    facilities: ["ICU", "Emergency", "Pharmacy", "Laboratory", "Radiology", "Dialysis"],
    rating: 4.0,
  },
];

// Mutation: Seed all Malaysian hospitals
export const seedHospitals = mutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();
    const insertedIds: string[] = [];

    for (const hospital of malaysianHospitals) {
      const id = await ctx.db.insert("hospitals", {
        ...hospital,
        createdAt: now,
        updatedAt: now,
      });
      insertedIds.push(id);
    }

    return {
      success: true,
      count: insertedIds.length,
      message: `Successfully seeded ${insertedIds.length} Malaysian hospitals`,
    };
  },
});

// Mutation: Clear all hospitals (useful for re-seeding)
export const clearHospitals = mutation({
  args: {},
  handler: async (ctx) => {
    const hospitals = await ctx.db.query("hospitals").collect();
    
    for (const hospital of hospitals) {
      await ctx.db.delete(hospital._id);
    }

    return {
      success: true,
      count: hospitals.length,
      message: `Successfully deleted ${hospitals.length} hospitals`,
    };
  },
});